histo1 = importdata('histogy1.txt','\t')

x1 = histo1(:,1)
y1 = histo1(:,2)

histo2 = importdata('histogy2.txt','\t')

x2 = histo2(:,1)
y2 = histo2(:,2)

hBar1 = bar(x2,y2)
hold on
hBar2 = bar(x1,y1)


xlim([10 70])
ylim([0 10])

set(gca                          , ...
  'Color'           , [1 1 1]    );
set(hBar1                          , ...
  'FaceColor'           , [.3 .3 .7]    ,...
    'EdgeColor'           , [.5 .5 .9]    ,...
    'LineWidth'       , .75           );


set(hBar2                          , ...
  'FaceColor'           , [.8 .3 .3]    ,...
    'EdgeColor'           , [1 .5 .5]    ,...
    'LineWidth'       , .75           );



hTitle  = title ('Maximum Radius of Gyration');
hXLabel = xlabel('Radius of Gyration (Å)'                     );
hYLabel = ylabel('Frequency'                      );

hLegend = legend( ...
  [hBar1, hBar2], ...
  'With Potential' , ...
  'Without Potential');

set( gca                       , ...
    'FontName'   , 'Verdana' );
set([hTitle, hXLabel, hYLabel], ...
    'FontName'   , 'Verdana');
set([hLegend, gca]             , ...
    'FontSize'   , 10           );
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 12          , ...
    'FontWeight' , 'bold'      );
set( hTitle                    , ...
    'FontSize'   , 16          , ...
    'FontWeight' , 'bold'      );

set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'YTick'       , 0:11:12, ...
  'LineWidth'   , 1         );